### ISSUE TITLE
Bugs and Test Error

### ISSUE THREAD

**Issue by frankecurtis** [kenjydem/CUTEST.py#13]
I could be wrong, but I believe there are two bugs:

1) In CUTEST.py/cutest/model/cutestmodel.py, there is an extra space before "pass" in the lines below:
`class SciPyCUTEstModel(SciPyNLPModel, CUTEstModel):
    """ CUTEst Model based on Scipy Model from NLP.py """
     pass`

2) In CUTEST.py/cutest/model/cutestmodel.py, I had to add the following line near the top:
`from nlp.model.scipymodel import SciPyNLPModel`

Ultimately, even after fixing these things, I cannot seem to get the test to work.  I see the following:

`Reading problem HS13...

 Problem name: HS13

 Double precision version will be formed

 The objective function uses 1 nonlinear group
 
 There is 1 nonlinear inequality constraint
 
 There are 2 variables bounded only from below 
 
 
 File successfully decoded
HS13.c:432:10: fatal error: 'cutest.h' file not found
#include "cutest.h"
         ^
1 error generated.
clang: error: no such file or directory: 'HS13.o'
Exception AttributeError: "'CUTEstModel' object has no attribute '_name'" in <object repr() failed> ignored`

Any ideas why it might not be able to find cutest.h?  I believe I have all dependencies installed and working correctly, including CUTEst itself.

**Comment by lambe** [comment]
The bugs you mentioned are fixed in PR #12.

I had the same error for cutest.h on my machine. I don't know how general the fix is, but I posted my solution to PR #14 for inspection. Perhaps @kenjydem could have a look?

**Comment by frankecurtis** [comment]
Thanks for the fast response!

I incorporated your changes to compile.py.  Unfortunately, however, I'm still seeing the same error re: cutest.h.

**Comment by kenjydem** [comment]
Hi guys,

When you import a problem with CUTEst.py, you actually compile a dynamic library with Cython executing by the function compile_SIF in the file compile.py in the repository cutest/tools.
 
For the process compile works successfully, you have to specify where is your path to libcutest.dylib and cutest.h in the file site.cfg. 

By default, the location of this information are generated with homebrew (Sorry, initially I've assumed that CUTEst was installed via homebrew ). So, I think your issue may come from there.

Try to change the file and let me know.

**Comment by frankecurtis** [comment]
Thanks.  Turns out, though, that I did install CUTEst with Homebrew.  I do see libcutest.dylib in /usr/local/lib and cutest.h in /usr/local/include.  I didn't edit the .cfg file, so I still see
`library_dirs = $(brew --prefix)/lib #/usr/local/lib
include_dirs = $(brew --prefix)/include  #/usr/local/include`
Any other ideas?

**Comment by kenjydem** [comment]
I just push some modifications on the site.cfg

Can you pull it and try again?

**Comment by frankecurtis** [comment]
That works for me!  Thanks.
