### ISSUE TITLE
Recognizing infinite bounds

### ISSUE THREAD

**Issue by lambe** [kenjydem/CUTEST.py#16]
In HS21MOD, several variables have explicit bounds of 1.0D+30 or -1.0D-30. When the problem is compiled in CUTEst itself, these bounds are identified as +infinity and -infinity, based on the command line output. However, because they are explicit numbers, they are treated as finite in the CUTEstModel. 

I don't know if there is a consistent rule in CUTEst about translating very large numbers as infinity. (Someone should look it up.) If there is, we should use the same rule in CUTEST.py. If there isn't, we should come with our own rule.

**Comment by dpo** [comment]
Yes we should. Infinity in CUTEst is 1.0D+20. Any bound beyond that should be considered as nonexistent.

**Comment by dpo** [comment]
Why was this closed? Is it already implemented?

**Comment by kenjydem** [comment]
It was fixed on the commit #8b4376f
