### ISSUE TITLE
'Segmentation fault' when calling cython interface

### ISSUE THREAD

**Issue by heeryerate** [kenjydem/CUTEST.py#17]
Thank you very much for developing the python interface!

I'm running on Mac OSX and using python3.6.  I believe I have all dependencies installed and working correctly, including CUTEst itself. I could work on problems in Matlab well.

Turns to this python interface, It bugs me a while to remove the error
```
ImportError: dlopen(./ROSENBR.so, 2): Symbol not found: __gfortran_cpu_time_4
  Referenced from: ./ROSENBR.so
  Expected in: flat namespace
 in ./ROSENBR.so
```
what I did is to add option `-lgfortran` in ./tools/compile.py when generate `.so` file. After doing this, I'm able to pass the following step at ./model/cutestmodel.py
```
cc = importlib.import_module(cython_lib_name)
```

However, for next step 
```
self.lib=cc.Cutest(name)
```
to start calling cython interface, it throws out `Segmentation fault`. Did I do something wrong? Any help would be much appreciated!

Attached is a piece of code when running  testing function `ROSENBR`
```
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cutest.model.cutestmodel import CUTEstModel
PySparse is not installed!
>>> model = CUTEstModel('ROSENBR')

 Problem name: ROSENBR

 Double precision version will be formed

 The objective function uses 1 linear group
 The objective function uses 1 nonlinear group

 There are 2 free variables


 File successfully decoded
[1]    34077 segmentation fault  python3
```

**Comment by dpo** [comment]
> `PySparse is not installed!`

Did you install PySparse?

**Comment by heeryerate** [comment]
thank you for your response! 

currently not installed. I tried to install PySparse, but it seems not supported on python3 yet [see csc-pysparse issue](https://github.com/rspeer/csc-pysparse/issues/1). I dug into it, tried to modify and install from source `pysparse-1.2-dev213`, but fails again. Considering the code can run without PySparse, I didn't put more efforts on the installation.

Is it necessary to have PySparse installed? If it is, I'll look into it again. Besides, since I tested over a small problem 'ROSENBR', I doubt if it needs sparse representation? please correct me if I'm wrong. Thank you!

**Comment by kenjydem** [comment]
PySparse is only used in the class PySparseCUTEstModel, so you should be able to import Rosenbrock. 

I've only used Cutest.py with Python 2.7. I believe the issue is from the cython and Python 3.6.  A link is probably missing. 

Have you checked your path in the site.template.cfg ?

**Comment by heeryerate** [comment]
I have the latest cython-0.27.3 installed for python3. Also I played with site.cfg but maybe I missed something and it didn't help...

currently I have
```bash
library_dirs = /usr/local/lib:/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/:/usr/local/lib/python3.6/site-packages/scipy/linalg/:/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zmq/backend/cython/
include_dirs = /usr/local/include
```
I also believe it might be some issues regarding python version. But since I'm having other code written well in python3, I do wish to make python3 works here unless impossible... please let me know your opinion, thank you!

**Comment by heeryerate** [comment]
Hi kenjydem, 

I tried some time, but still can't figure out the issue. I installed python2.7 version, and now it works. There should be error regarding cython and python3 although I'm not sure where..

please close this issue then, thank you :)

**Comment by kenjydem** [comment]
Sorry that I couldn't help your more with Python3 ! Have fun with cutest!

PS: Be careful, if you import more than one cutest problem at the same file, you'll have an issue (only for OSX user). Just use one problem at the time.

**Comment by heeryerate** [comment]
@kenjydem sorry I missed your reply. Thank you very much for your reminder! 👍 👍
