### ISSUE TITLE
SIF file name issues

### ISSUE THREAD

**Issue by lambe** [kenjydem/CUTEST.py#9]
SIF files that start with a number (e.g., 3pk) and containing hyphens (e.g., het-z) cannot be compiled by cython and raise the following error:

'''
Error compiling Cython file:
------------------------------------------------------------
...
#-*- coding: utf-8; mode: python; tab-width: 4; -*-
^
------------------------------------------------------------

HET-Z.pyx:1:0: 'HET-Z' is not a valid module name
'''

I don't know if this is a cython-specific issue or just a CUTEST.py issue.

To replicate the issue, just put one of the above problem names in 'test_cutest.py' and run.

**Comment by kenjydem** [comment]
Thanks again for your feedback, the issue was caused during Cython compilation. Cython's files can not contain hyphens or start by a number. 

I just add a name verification in the compile method to be sure to not have this conflict anymore. For SIF files starting with a number, I have seen only 3PK.SIF and 10FOLDTR.SIF. 

Can you confirm me they are the only SIF files starting with a number?

**Comment by lambe** [comment]
Yes, those are the only SIF files that start with a number. Here's the list of files that contain a hyphen:
CONT5-QP.SIF
CONT6-QQ.SIF
C-RELOAD.SIF
HET-Z.SIF
HUES-MOD.SIF
S277-280.SIF
S316-322.SIF
TRY-B.SIF
ZAMB2-10.SIF
ZAMB2-11.SIF
ZAMB2-8.SIF
ZAMB2-9.SIF

**Comment by kenjydem** [comment]
For the files that contains a hyphen, I don't need to save their names. I tried yesterday a couple of them, it works fine for me. 

Can you confirm it?

**Comment by dpo** [comment]
CUTEst.py should accept any file name that starts with a digit, not just those that currently exist. New SIF files are submitted once in a while.

**Comment by kenjydem** [comment]
I've just modified the compiling method to automatically accept any file name that starts with a digit.

**Comment by lambe** [comment]
I tested both cases and they work now. Thanks, Kenjy! Closing the issue now.
